map_type: costmap

obstacle_range: 4.5
raytrace_range: 4.5
cost_scaling_factor: 2

transform_tolerance: 3

inflation_radius: 0.4

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /rob_bot/laser/scan, marking: true, clearing: true}