local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 5.0
   publish_frequency: 2.0
   width: 5.0
   height: 5.0
   resolution: 0.05
   static_map: false
   rolling_window: true
   xy_goal_tolerance: 0.03
   yaw_goal_tolerance: 0.01